### ISSUE TITLE
SUPPORT_* deprecated in 2025.10

### ISSUE THREAD

**Issue by cyriax** [DominikWrobel/viomise#1]
Hello there,

here is the mandatory deprecation issue for vacuums regarding the SUPPORT_* functions:

`SUPPORT_RETURN_HOME was used from viomise, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.RETURN_HOME instead, please report it to the author of the 'viomise' custom integration
SUPPORT_SEND_COMMAND was used from viomise, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.SEND_COMMAND instead, please report it to the author of the 'viomise' custom integration
SUPPORT_START was used from viomise, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.START instead, please report it to the author of the 'viomise' custom integration
SUPPORT_STATE was used from viomise, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.STATE instead, please report it to the author of the 'viomise' custom integration
SUPPORT_STOP was used from viomise, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.STOP instead, please report it to the author of the 'viomise' custom integration`

Since VacuumEntityFeature is already in the import and implemented in the "SUPPORT_XIAOMI" part, removing

`    SUPPORT_BATTERY,
    SUPPORT_FAN_SPEED,
    SUPPORT_LOCATE,
    SUPPORT_PAUSE,
    SUPPORT_RETURN_HOME,
    SUPPORT_SEND_COMMAND,
    SUPPORT_START,
    SUPPORT_STATE,
    SUPPORT_STOP,
   StateVacuumEntity,`

from the import should do the trick once necessary.

**Comment by DominikWrobel** [comment]
Fixed in version 1.3
